### ISSUE TITLE
Display current table filters on data and ability to clear filters

### ISSUE THREAD

**Issue by tbock** [USEPA/Scribe-Data-View-Tool#10]
Once you set a filter in the table its hard to tell where you set that filter and for what value. So need to display a kind of summary of current filters somewhere.  

Possibly using chips: https://material.angular.io/components/chips/overview

With the ability to clear any filter identify in the chip by click on a X on the chip.

**Comment by tbock** [comment]
Put chips somewhere in here
![image](https://user-images.githubusercontent.com/4040295/74271199-55329980-4cc1-11ea-8f24-fa07fb65c276.png)

**Comment by tommckennon** [comment]
Snapshot of implementation:
![ScribeToolActiveFilters](https://user-images.githubusercontent.com/28331071/74771100-6d1a9800-5242-11ea-9567-a6817dd247a8.JPG)
