### ISSUE TITLE
Highlight corresponding rows when map point is selected

### ISSUE THREAD

**Issue by tommckennon** [USEPA/Scribe-Data-View-Tool#26]
When a map point is selected, highlight the corresponding records in the table.

**Comment by tommckennon** [comment]
@tbock , this is the last mentioned enhancement that was brought up during the last demo. It's in progress.

**Comment by jlherring** [comment]
This seems to be working when you click a single point, but not when you use the lasso to select multiple points

**Comment by jlherring** [comment]
It is a little weird that selecting one point highlights the records but selecting multiple points filters the records, but we'll go with it for now
