### ISSUE TITLE
Update field aliases and defaults for sample locations

### ISSUE THREAD

**Issue by jlherring** [USEPA/Scribe-Data-View-Tool#29]
Still need to clean up field names for the Sample Point Locations Section (not just Lab Analyte Results)

![image](https://user-images.githubusercontent.com/17882165/76358009-1fe49000-62ef-11ea-8b16-5846d2851154.png)

**Here's the list of fields:**
- [x] SamplesID: Sample ID
- [ ] Site Number
- [ ] EventID
- [x] Sample Number
- [x] Sample Date
- [x] SampleTime
- [x] Location
- [ ] Sub_Location
- [x] Matrix
- [ ] Sample Type
- [ ] SampleMedia
- [ ] SampleCollection
- [ ] SampleType
- [ ] Activity
- [x] Samp_Depth
- [ ] Samp_Depth_To
- [x] Samp_Depth_Units
- [ ] Volume
- [ ] Volume_Units
- [ ] Samp_Concentration
- [ ] Sampler
- [ ] Witness
- [ ] LinkSampleNo
- [ ] Image_Path
- [ ] Remarks
- [ ] LabResultsAvailable
- [ ] Task_ID
- [ ] Date Input
- [ ] Date_Edit
- [ ] Edited_By
- [ ] SiteID
- [ ] Site_Numb
- [ ] Option_Period
- [x] Site_Name
- [x] Area
- [ ] Site_State
- [ ] Site_Phone
- [ ] Description
- [ ] Site_Action
- [ ] DO_Number
- [ ] CERCLIS
- [ ] AccountCode
- [ ] ProjectCode
- [ ] Numeric_Tags
- [ ] CaseNumber
- [ ] Next_CLP_Sample_No
- [ ] Next_Tag
- [ ] Region_Tag_Prefix
- [ ] Response_Authority
- [ ] NPL_Status
- [ ] DASNumber
- [ ] EPARegionNumber
- [ ] EPA_OrgName
- [ ] EPAContract_No
- [ ] EPAProj_No
- [ ] EPAContact
- [ ] EPAPhone
- [ ] Contract_Name
- [x] Contractor
- [x] CTRContact
- [ ] Address1
- [ ] Address2
- [ ] City
- [ ] State
- [ ] Zip
- [ ] CTRPhone
- [ ] CTRWano
- [ ] Unit_Of_Meas
- [ ] Control_No
- [ ] VER_NO
- [ ] Template_File_Path
- [ ] ScribeNetProjectID
- [ ] ScribeNetCustomerID
- [ ] CLP_Tag_Mask
- [ ] Project_Default
- [ ] LocationID
- [ ] PropertyID
- [ ] LocationDescription
- [ ] LocationZone
- [x] Latitude
- [x] Longitude
- [ ] Altitude
- [ ] GPS_PDOP
- [ ] GPS_CorrectionType
- [ ] GPS_Date
- [ ] GPS_Time
- [ ] GPS_Collected_By
- [ ] GPS_Comment
- [ ] GPS_Phase
- [ ] Northing
- [ ] Easting
- [ ] Datum
- [ ] GeoMethod
- [ ] GeoScale
- [ ] Surf_Elev
- [ ] Surf_Units
- [ ] ElevMethod
- [ ] ElevDatum
- [ ] Coord_Sys_Desc
- [ ] LocationComment
- [ ] Location_Image_Path

**Comment by tommckennon** [comment]
This has been resolved for both the display visible fields and filter aliases. Snapshot:
![image](https://user-images.githubusercontent.com/28331071/76466990-db67fb80-63a5-11ea-8393-2f4b4a01c6ba.png)
So going to move to review.

**Comment by jlherring** [comment]
Still not seeing this update in prod

**Comment by jlherring** [comment]
Lasttttttt tweak in the Sample Point Locations and then we should be good to go:
![image](https://user-images.githubusercontent.com/17882165/90638944-fa43a700-e1fb-11ea-9e48-d872b3a1c931.png)

**Comment by tommckennon** [comment]
Easy fix.
