### ISSUE TITLE
Ability to switch to GeoPlatform for additional analysis

### ISSUE THREAD

**Issue by jlherring** [USEPA/Scribe-Data-View-Tool#33]
Anything more complicated than symbolizing MDL above/below for given analytes - move the user to a layer in the GeoPlatform

Per discussion on 10/26, the title and description format set for the published feature layer services is as follows: 
Title: **[Project name] ([Number]) Scribe Project Feature Layer** 
Description: **Projects: [ ], Filters: [ ]**

**Comment by jlherring** [comment]
Can potentially push services to the GPO, but has some complications. Need to make sure users know where the layer is going to go find it in their account and need to know that it is just a snapshot of the data. (If contractors update the project, the user will not automatically get those updates.)

**Comment by tbock** [comment]
Publishing not working when encountering None for latitude or longitude.  Please revise and submit PR. @tommckennon

**Comment by tommckennon** [comment]
@tbock , I just saw the email that notified me on your last message here. I went ahead and already merged the update/fix mentioned for this. As always, I include the issue number with my commits, so what I did is tagged right above this comment :).
