### ISSUE TITLE
Legend Updates

### ISSUE THREAD

**Issue by jlherring** [USEPA/Scribe-Data-View-Tool#39]
Cheryl on 5/8: Don't like halos around numbers in the legend. Need to update look/feel of the legend

![image](https://user-images.githubusercontent.com/17882165/81425057-debd0080-9124-11ea-8f42-6b9bac47101d.png)

Also need to change "MDL" text. Cheryl thinking this is actually Method Detection Limit: "The method detection limit (MDL) is defined as the minimum concentration of a substance that can be measured and reported with 99% confidence that the analyte concentration is greater than zero and is determined from analysis of a sample in a given matrix containing the analyte." So she's thinking we don't want "MDL" in the language.

Change "To symbolize samples by MDL... " text to "Provide a value below to symbolize samples above or below a specific threshold:"

Change "MDL Threshold between X and Y" to "Sample values range from X to Y"

**Comment by jlherring** [comment]
Swap to this? https://developers.arcgis.com/javascript/latest/sample-code/sandbox/index.html?sample=visualization-sm-color-mesh

**Comment by tbock** [comment]
removed this functionality for now.
