### ISSUE TITLE
Select project from the map

### ISSUE THREAD

**Issue by jlherring** [USEPA/Scribe-Data-View-Tool#43]
Matt Small would like to be able to select a project from the map, rather than only using the project drop-down. RPMs do not always know the name of their Scribe project, but know where it is located. 

Maybe use the project service from the COP as a starting point?

**Comment by tbock** [comment]
scribe services from server but embedded in agol is here https://epa.maps.arcgis.com/home/item.html?id=add9432d507146e7abf3351efa097b99#overview @tommckennon

**Comment by jlherring** [comment]
We need a little more context in the interface. Not super intuitive yet. See screen shot below - includes updated text and a different lasso icon (this is the icon used in WABs/editor tools)

![image](https://user-images.githubusercontent.com/17882165/88218522-2afce480-cc2e-11ea-974a-fd84a49d32e6.png)
