### ISSUE TITLE
Update description

### ISSUE THREAD

**Issue by jlherring** [USEPA/Scribe-Data-View-Tool#47]
We updated the name, but never updated the description: 

"Welcome to the Scribe Data Explorer! Search for and interact with projects from USEPA ERT's [Scribe](https://response.epa.gov/site/site_profile.aspx?site_id=ScribeGIS) database system." Select projects from the drop-down or use the "Select Projects on Map" button to get started.

![image](https://user-images.githubusercontent.com/17882165/88214774-b3788680-cc28-11ea-972a-93a9288aa014.png)

**Comment by jlherring** [comment]
Looks like we have an extra space between the m and the period:
![image](https://user-images.githubusercontent.com/17882165/90258668-e02e5100-de16-11ea-8418-0bb6b20c219e.png)

**Comment by tommckennon** [comment]
Easy fix.
