### ISSUE TITLE
Select project from map - load/select issues

### ISSUE THREAD

**Issue by jlherring** [USEPA/Scribe-Data-View-Tool#53]
Why are we loading on 0,0? Can we load on R9? That it was before, not sure what's happening here

![image](https://user-images.githubusercontent.com/17882165/104643975-2fed9e80-567b-11eb-8f53-3ddd0ca4cf2e.png)

Not to measure that the selection isn't working at all anymore. Cannot click a point and points inside my lasso aren't working anymore

**Comment by tbock** [comment]
Now starting at extent of projects or at least centered on CA.
