### ISSUE TITLE
Review of sample point color code keys based on both Sample Type and MDL values

### ISSUE THREAD

**Issue by tommckennon** [USEPA/Scribe-Data-View-Tool#6]
Verify these color code keys by displaying them in a legend.
- air: 
MDL = 0: '#00b7ff', 
MDL > 0 && MDL <= 10: '#0062a8', 
MDL > 10 && MDL <= 100: '#00497c'
- water:,
MDL = 0: '#6040ff', 
MDL > 0 && MDL <= 10: '#0062a8', 
MDL > 10 && MDL <= 100: ''#392699'
- soil:
MDL = 0: '#b59273', 
MDL > 0 && MDL <= 10: '#ffb339', 
MDL > 10 && MDL <= 100: ''#6b2600'

**Comment by jlherring** [comment]
No longer needed
